#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Aug 22, 2018 03:35:55 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global display_contour
    display_contour = StringVar()
    global plot_residual
    plot_residual = StringVar()
    global johnson_mean
    johnson_mean = StringVar()
    johnson_mean.set(0.0)
    global johnson_var
    johnson_var = StringVar()
    johnson_var.set(1.0)
    global krylov_tol
    krylov_tol = StringVar()
    krylov_tol.set("1e-7")
    global krylov_max_iter
    krylov_max_iter = StringVar()
    krylov_max_iter.set(1000)
    global krylov_method
    krylov_method = StringVar()
    krylov_method.set("gmres")

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Adv_settings
    Adv_settings.vp_start_gui()


