#############################################################################
# Generated by PAGE version 4.14
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.tLa40
    set site_3_0 $base.tLa45
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 290x389+755+317
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1170
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Advanced settings"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font TkDefaultFont
    ttk::checkbutton $top.tCh38 \
        -variable display_contour -takefocus {} \
        -text {Display contours of ACF.} 
    vTcl:DefineAlias "$top.tCh38" "TCheckbutton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background #d9d9d9
    ttk::style configure TCheckbutton -foreground #000000
    ttk::style configure TCheckbutton -font TkDefaultFont
    ttk::checkbutton $top.tCh39 \
        -variable plot_residual -takefocus {} \
        -text {Plot residual on each iteration.} 
    vTcl:DefineAlias "$top.tCh39" "TCheckbutton2" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tLa40 \
        -text {Johnson distribution} -width 270 -height 95 
    vTcl:DefineAlias "$top.tLa40" "TLabelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tLa40
    ttk::label $site_3_0.tLa41 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text Mean: 
    vTcl:DefineAlias "$site_3_0.tLa41" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi42 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from -100000.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable johnson_mean -to 100000.0 
    vTcl:DefineAlias "$site_3_0.spi42" "Spinbox1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa43 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text Variance: 
    vTcl:DefineAlias "$site_3_0.tLa43" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi44 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from 0.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable johnson_var -to 1000.0 
    vTcl:DefineAlias "$site_3_0.spi44" "Spinbox2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tLa41 \
        -in $site_3_0 -x 15 -y 23 -width 40 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi42 \
        -in $site_3_0 -x 95 -y 23 -width 160 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa43 \
        -in $site_3_0 -x 15 -y 62 -width 58 -height 13 -anchor nw \
        -bordermode ignore 
    place $site_3_0.spi44 \
        -in $site_3_0 -x 95 -y 60 -width 160 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tLa45 \
        -text {Krylov non-linear system solver} -width 270 -height 145 
    vTcl:DefineAlias "$top.tLa45" "TLabelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tLa45
    ttk::label $site_3_0.tLa46 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text Tolerance: 
    vTcl:DefineAlias "$site_3_0.tLa46" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $site_3_0.tEn47 \
        -textvariable krylov_tol -foreground {} -background {} -takefocus {} \
        -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn47" "TEntry1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa48 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text {Maximum iterations:} 
    vTcl:DefineAlias "$site_3_0.tLa48" "TLabel4" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi50 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from 1.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable krylov_max_iter -to 10000000.0 
    vTcl:DefineAlias "$site_3_0.spi50" "Spinbox3" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa51 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text Method: 
    vTcl:DefineAlias "$site_3_0.tLa51" "TLabel5" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_3_0.tCo52 \
        -textvariable krylov_method -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo52" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tLa46 \
        -in $site_3_0 -x 10 -y 30 -width 74 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn47 \
        -in $site_3_0 -x 95 -y 30 -width 160 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa48 \
        -in $site_3_0 -x 10 -y 60 -width 144 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi50 \
        -in $site_3_0 -x 150 -y 60 -width 103 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa51 \
        -in $site_3_0 -x 10 -y 90 -width 64 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo52 \
        -in $site_3_0 -x 95 -y 90 -width 160 -height 20 -anchor nw \
        -bordermode ignore 
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu53 \
        -takefocus {} -text Close 
    vTcl:DefineAlias "$top.tBu53" "TButton1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tCh38 \
        -in $top -x 20 -y 20 -anchor nw -bordermode ignore 
    place $top.tCh39 \
        -in $top -x 20 -y 50 -anchor nw -bordermode ignore 
    place $top.tLa40 \
        -in $top -x 10 -y 80 -width 270 -relwidth 0 -height 95 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa45 \
        -in $top -x 10 -y 189 -width 270 -relwidth 0 -height 145 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu53 \
        -in $top -x 100 -y 350 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

