#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Aug 09, 2018 02:26:26 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import V2_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    V2_support.set_Tk_var()
    top = MARS (root)
    V2_support.init(root, top)
    root.mainloop()

w = None
def create_MARS(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    V2_support.set_Tk_var()
    top = MARS (w)
    V2_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_MARS():
    global w
    w.destroy()
    w = None


class MARS:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("490x320+831+270")
        top.title("MARS")
        top.configure(highlightcolor="black")



        self.Labelframe1 = LabelFrame(top)
        self.Labelframe1.place(relx=0.0, rely=0.0, relheight=0.39, relwidth=0.53)

        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(text='''Surface parameters''')
        self.Labelframe1.configure(width=260)

        self.TLabel1 = ttk.Label(self.Labelframe1)
        self.TLabel1.place(relx=0.04, rely=0.17, height=19, width=134, y=-10
                , h=5)
        self.TLabel1.configure(background="#d9d9d9")
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(font="TkDefaultFont")
        self.TLabel1.configure(relief=FLAT)
        self.TLabel1.configure(text='''Number of attempts:''')
        self.TLabel1.configure(width=134)

        self.TLabel2 = ttk.Label(self.Labelframe1)
        self.TLabel2.place(relx=0.04, rely=0.43, height=19, width=136, y=-10
                , h=5)
        self.TLabel2.configure(background="#d9d9d9")
        self.TLabel2.configure(foreground="#000000")
        self.TLabel2.configure(font="TkDefaultFont")
        self.TLabel2.configure(relief=FLAT)
        self.TLabel2.configure(text='''Surface size N x M:''')
        self.TLabel2.configure(width=136)

        self.TLabel3 = ttk.Label(self.Labelframe1)
        self.TLabel3.place(relx=0.73, rely=0.43, height=19, width=13, y=-10, h=5)

        self.TLabel3.configure(background="#d9d9d9")
        self.TLabel3.configure(foreground="#000000")
        self.TLabel3.configure(font="TkDefaultFont")
        self.TLabel3.configure(relief=FLAT)
        self.TLabel3.configure(text='''x''')

        self.TLabel4 = ttk.Label(self.Labelframe1)
        self.TLabel4.place(relx=0.73, rely=0.7, height=19, width=9, y=-10, h=5)
        self.TLabel4.configure(background="#d9d9d9")
        self.TLabel4.configure(foreground="#000000")
        self.TLabel4.configure(font="TkDefaultFont")
        self.TLabel4.configure(relief=FLAT)
        self.TLabel4.configure(text=''',''')

        self.TLabel6 = ttk.Label(self.Labelframe1)
        self.TLabel6.place(relx=0.04, rely=0.7, height=19, width=107, y=-10, h=5)

        self.TLabel6.configure(background="#d9d9d9")
        self.TLabel6.configure(foreground="#000000")
        self.TLabel6.configure(font="TkDefaultFont")
        self.TLabel6.configure(relief=FLAT)
        self.TLabel6.configure(text='''Spacing dx, dy:''')

        self.Spinbox1 = Spinbox(self.Labelframe1, from_=1.0, to=1000.0)
        self.Spinbox1.place(relx=0.58, rely=0.43, relheight=0.17, relwidth=0.14
                , y=-10, h=5)
        self.Spinbox1.configure(activebackground="#f9f9f9")
        self.Spinbox1.configure(background="white")
        self.Spinbox1.configure(from_="1.0")
        self.Spinbox1.configure(highlightbackground="black")
        self.Spinbox1.configure(selectbackground="#c4c4c4")
        self.Spinbox1.configure(to="1000.0")
        self.Spinbox1.configure(width=36)

        self.Spinbox2 = Spinbox(self.Labelframe1, from_=1.0, to=1000.0)
        self.Spinbox2.place(relx=0.81, rely=0.43, relheight=0.17, relwidth=0.14
                , y=-10, h=5)
        self.Spinbox2.configure(activebackground="#f9f9f9")
        self.Spinbox2.configure(background="white")
        self.Spinbox2.configure(from_="1.0")
        self.Spinbox2.configure(highlightbackground="black")
        self.Spinbox2.configure(selectbackground="#c4c4c4")
        self.Spinbox2.configure(to="1000.0")
        self.Spinbox2.configure(width=37)

        self.Spinbox3 = Spinbox(self.Labelframe1, from_=1.0, to=1000.0)
        self.Spinbox3.place(relx=0.58, rely=0.7, relheight=0.17, relwidth=0.14
                , y=-10, h=5)
        self.Spinbox3.configure(activebackground="#f9f9f9")
        self.Spinbox3.configure(background="white")
        self.Spinbox3.configure(from_="1.0")
        self.Spinbox3.configure(highlightbackground="black")
        self.Spinbox3.configure(selectbackground="#c4c4c4")
        self.Spinbox3.configure(to="1000.0")

        self.Spinbox4 = Spinbox(self.Labelframe1, from_=1.0, to=1000.0)
        self.Spinbox4.place(relx=0.81, rely=0.7, relheight=0.17, relwidth=0.14
                , y=-10, h=5)
        self.Spinbox4.configure(activebackground="#f9f9f9")
        self.Spinbox4.configure(background="white")
        self.Spinbox4.configure(from_="1.0")
        self.Spinbox4.configure(highlightbackground="black")
        self.Spinbox4.configure(selectbackground="#c4c4c4")
        self.Spinbox4.configure(to="1000.0")

        self.Spinbox5 = Spinbox(self.Labelframe1, from_=1.0, to=100.0)
        self.Spinbox5.place(relx=0.58, rely=0.17, relheight=0.17, relwidth=0.37
                , y=-10, h=5)
        self.Spinbox5.configure(activebackground="#f9f9f9")
        self.Spinbox5.configure(background="white")
        self.Spinbox5.configure(from_="1.0")
        self.Spinbox5.configure(highlightbackground="black")
        self.Spinbox5.configure(selectbackground="#c4c4c4")
        self.Spinbox5.configure(state=DISABLED)
        self.Spinbox5.configure(to="100.0")
        self.Spinbox5.configure(width=97)

        self.Labelframe2 = LabelFrame(top)
        self.Labelframe2.place(relx=0.0, rely=0.41, relheight=0.42
                , relwidth=0.49)
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(text='''Height distribution''')
        self.Labelframe2.configure(width=240)

        self.TLabel5 = ttk.Label(self.Labelframe2)
        self.TLabel5.place(relx=0.04, rely=0.24, height=13, width=79, y=-10, h=5)

        self.TLabel5.configure(background="#d9d9d9")
        self.TLabel5.configure(foreground="#000000")
        self.TLabel5.configure(font="TkDefaultFont")
        self.TLabel5.configure(relief=FLAT)
        self.TLabel5.configure(text='''Rms height:''')

        self.TLabel7 = ttk.Label(self.Labelframe2)
        self.TLabel7.place(relx=0.04, rely=0.48, height=13, width=65, y=-10, h=5)

        self.TLabel7.configure(background="#d9d9d9")
        self.TLabel7.configure(foreground="#000000")
        self.TLabel7.configure(font="TkDefaultFont")
        self.TLabel7.configure(relief=FLAT)
        self.TLabel7.configure(text='''Skewness:''')

        self.TLabel8 = ttk.Label(self.Labelframe2)
        self.TLabel8.place(relx=0.04, rely=0.72, height=13, width=65, y=-10, h=5)

        self.TLabel8.configure(background="#d9d9d9")
        self.TLabel8.configure(foreground="#000000")
        self.TLabel8.configure(font="TkDefaultFont")
        self.TLabel8.configure(relief=FLAT)
        self.TLabel8.configure(text='''Kurtosis:''')

        self.Spinbox6 = Spinbox(self.Labelframe2, from_=1.0, to=1000.0)
        self.Spinbox6.place(relx=0.46, rely=0.22, relheight=0.15, relwidth=0.4
                , y=-10, h=5)
        self.Spinbox6.configure(activebackground="#f9f9f9")
        self.Spinbox6.configure(background="white")
        self.Spinbox6.configure(from_="1.0")
        self.Spinbox6.configure(highlightbackground="black")
        self.Spinbox6.configure(selectbackground="#c4c4c4")
        self.Spinbox6.configure(state=DISABLED)
        self.Spinbox6.configure(to="1000.0")

        self.Spinbox7 = Spinbox(self.Labelframe2, from_=0.0, to=100.0)
        self.Spinbox7.place(relx=0.46, rely=0.48, relheight=0.15, relwidth=0.4
                , y=-10, h=5)
        self.Spinbox7.configure(activebackground="#f9f9f9")
        self.Spinbox7.configure(background="white")
        self.Spinbox7.configure(highlightbackground="black")
        self.Spinbox7.configure(increment="0.1")
        self.Spinbox7.configure(selectbackground="#c4c4c4")
        self.Spinbox7.configure(to="100.0")

        self.Spinbox8 = Spinbox(self.Labelframe2, from_=0.0, to=100.0)
        self.Spinbox8.place(relx=0.46, rely=0.72, relheight=0.15, relwidth=0.4
                , y=-10, h=5)
        self.Spinbox8.configure(activebackground="#f9f9f9")
        self.Spinbox8.configure(background="white")
        self.Spinbox8.configure(highlightbackground="black")
        self.Spinbox8.configure(increment="0.1")
        self.Spinbox8.configure(selectbackground="#c4c4c4")
        self.Spinbox8.configure(to="100.0")

        self.Labelframe4 = LabelFrame(top)
        self.Labelframe4.place(relx=0.51, rely=0.41, relheight=0.42
                , relwidth=0.49)
        self.Labelframe4.configure(relief=GROOVE)
        self.Labelframe4.configure(text='''Correlation function''')
        self.Labelframe4.configure(width=240)

        self.TLabel9 = ttk.Label(self.Labelframe4)
        self.TLabel9.place(relx=0.04, rely=0.24, height=13, width=37, y=-10, h=5)

        self.TLabel9.configure(background="#d9d9d9")
        self.TLabel9.configure(foreground="#000000")
        self.TLabel9.configure(font="TkDefaultFont")
        self.TLabel9.configure(relief=FLAT)
        self.TLabel9.configure(text='''Type:''')

        self.TCombobox1 = ttk.Combobox(self.Labelframe4)
        self.TCombobox1.place(relx=0.38, rely=0.24, relheight=0.16, relwidth=0.52
                , y=-10, h=5)
        self.TCombobox1.configure(textvariable=V2_support.combobox)
        self.TCombobox1.configure(width=125)
        self.TCombobox1.configure(takefocus="")
        self.TCombobox1.configure(cursor="arrow")

        self.TLabel10 = ttk.Label(self.Labelframe4)
        self.TLabel10.place(relx=0.04, rely=0.48, height=13, width=44, y=-10
                , h=5)
        self.TLabel10.configure(background="#d9d9d9")
        self.TLabel10.configure(foreground="#000000")
        self.TLabel10.configure(font="TkDefaultFont")
        self.TLabel10.configure(relief=FLAT)
        self.TLabel10.configure(text='''n x m:''')

        self.TLabel11 = ttk.Label(self.Labelframe4)
        self.TLabel11.place(relx=0.6, rely=0.48, height=19, width=16, y=-10, h=5)

        self.TLabel11.configure(background="#d9d9d9")
        self.TLabel11.configure(foreground="#000000")
        self.TLabel11.configure(font="TkDefaultFont")
        self.TLabel11.configure(relief=FLAT)
        self.TLabel11.configure(text='''x''')

        self.TLabel12 = ttk.Label(self.Labelframe4)
        self.TLabel12.place(relx=0.04, rely=0.72, height=13, width=44, y=-10
                , h=5)
        self.TLabel12.configure(background="#d9d9d9")
        self.TLabel12.configure(foreground="#000000")
        self.TLabel12.configure(font="TkDefaultFont")
        self.TLabel12.configure(relief=FLAT)
        self.TLabel12.configure(text='''Alpha:''')

        self.Spinbox9 = Spinbox(self.Labelframe4, from_=1.0, to=1000.0)
        self.Spinbox9.place(relx=0.38, rely=0.48, relheight=0.16, relwidth=0.19
                , y=-10, h=5)
        self.Spinbox9.configure(activebackground="#f9f9f9")
        self.Spinbox9.configure(background="white")
        self.Spinbox9.configure(from_="1.0")
        self.Spinbox9.configure(highlightbackground="black")
        self.Spinbox9.configure(selectbackground="#c4c4c4")
        self.Spinbox9.configure(to="1000.0")

        self.Spinbox10 = Spinbox(self.Labelframe4, from_=1.0, to=1000.0)
        self.Spinbox10.place(relx=0.71, rely=0.48, relheight=0.16, relwidth=0.19
                , y=-10, h=5)
        self.Spinbox10.configure(activebackground="#f9f9f9")
        self.Spinbox10.configure(background="white")
        self.Spinbox10.configure(from_="1.0")
        self.Spinbox10.configure(highlightbackground="black")
        self.Spinbox10.configure(selectbackground="#c4c4c4")
        self.Spinbox10.configure(to="1000.0")

        self.Spinbox11 = Spinbox(self.Labelframe4, from_=0.0, to=100.0)
        self.Spinbox11.place(relx=0.38, rely=0.72, relheight=0.16, relwidth=0.52
                , y=-10, h=5)
        self.Spinbox11.configure(activebackground="#f9f9f9")
        self.Spinbox11.configure(background="white")
        self.Spinbox11.configure(highlightbackground="black")
        self.Spinbox11.configure(increment="0.5")
        self.Spinbox11.configure(selectbackground="#c4c4c4")
        self.Spinbox11.configure(to="100.0")

        self.TButton1 = ttk.Button(top)
        self.TButton1.place(relx=0.02, rely=0.88, height=25, width=133)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Generate surface''')
        self.TButton1.configure(width=133)

        self.TButton2 = ttk.Button(top)
        self.TButton2.place(relx=0.6, rely=0.88, height=25, width=96)
        self.TButton2.configure(takefocus="")
        self.TButton2.configure(text='''Diagnostics''')
        self.TButton2.configure(width=96)
        self.TButton2.configure(state=DISABLED)

        self.TButton3 = ttk.Button(top)
        self.TButton3.place(relx=0.82, rely=0.88, height=25, width=76)
        self.TButton3.configure(takefocus="")
        self.TButton3.configure(text='''Save as''')
        self.TButton3.configure(state=DISABLED)

        self.TButton4 = ttk.Button(top)
        self.TButton4.place(relx=0.31, rely=0.88, height=25, width=130)
        self.TButton4.configure(takefocus="")
        self.TButton4.configure(text='''Advanced settings''')

        self.TLabelframe1 = ttk.Labelframe(top)
        self.TLabelframe1.place(relx=0.55, rely=0.0, relheight=0.39
                , relwidth=0.45)
        self.TLabelframe1.configure(text='''Program output''')
        self.TLabelframe1.configure(width=220)

        self.Text1 = Text(self.TLabelframe1)
        self.Text1.place(relx=0.05, rely=0.17, relheight=0.72, relwidth=0.91
                , y=-10, h=5)
        self.Text1.configure(background="white")
        self.Text1.configure(cursor="arrow")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(state=DISABLED)
        self.Text1.configure(width=200)
        self.Text1.configure(wrap=WORD)






if __name__ == '__main__':
    vp_start_gui()



