#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Aug 07, 2018 03:16:48 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import V2_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    V2_support.set_Tk_var()
    top = MARS (root)
    V2_support.init(root, top)
    root.mainloop()

w = None
def create_MARS(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    V2_support.set_Tk_var()
    top = MARS (w)
    V2_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_MARS():
    global w
    w.destroy()
    w = None


class MARS:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("320x320+521+216")
        top.title("MARS")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Labelframe1 = LabelFrame(top)
        self.Labelframe1.place(relx=0.0, rely=0.0, relheight=0.39, relwidth=1.0)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Surface parameters''')
        self.Labelframe1.configure(background="#d9d9d9")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")
        self.Labelframe1.configure(width=325)

        self.TEntry1 = ttk.Entry(self.Labelframe1)
        self.TEntry1.place(relx=0.41, rely=0.19, relheight=0.17, relwidth=0.23
                , y=-12, h=6)
        READONLY = 'readonly'
        self.TEntry1.configure(state=READONLY)
        self.TEntry1.configure(width=76)
        self.TEntry1.configure(takefocus="")
        self.TEntry1.configure(cursor="arrow")

        self.TLabel1 = ttk.Label(self.Labelframe1)
        self.TLabel1.place(relx=0.03, rely=0.19, height=19, width=114, y=-12
                , h=6)
        self.TLabel1.configure(background="#d9d9d9")
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(font="TkDefaultFont")
        self.TLabel1.configure(relief=FLAT)
        self.TLabel1.configure(text='''Number of attempts:''')
        self.TLabel1.configure(width=114)

        self.TEntry2 = ttk.Entry(self.Labelframe1)
        self.TEntry2.place(relx=0.41, rely=0.46, relheight=0.17, relwidth=0.08
                , y=-12, h=6)
        self.TEntry2.configure(width=26)
        self.TEntry2.configure(takefocus="")
        self.TEntry2.configure(cursor="arrow")

        self.TLabel2 = ttk.Label(self.Labelframe1)
        self.TLabel2.place(relx=0.03, rely=0.47, height=19, width=106, y=-12
                , h=6)
        self.TLabel2.configure(background="#d9d9d9")
        self.TLabel2.configure(foreground="#000000")
        self.TLabel2.configure(font="TkDefaultFont")
        self.TLabel2.configure(relief=FLAT)
        self.TLabel2.configure(text='''Surface size N x M:''')
        self.TLabel2.configure(width=106)

        self.TEntry3 = ttk.Entry(self.Labelframe1)
        self.TEntry3.place(relx=0.56, rely=0.46, relheight=0.17, relwidth=0.08
                , y=-12, h=6)
        self.TEntry3.configure(width=26)
        self.TEntry3.configure(takefocus="")
        self.TEntry3.configure(cursor="arrow")

        self.TLabel3 = ttk.Label(self.Labelframe1)
        self.TLabel3.place(relx=0.5, rely=0.46, height=19, width=13, y=-12, h=6)
        self.TLabel3.configure(background="#d9d9d9")
        self.TLabel3.configure(foreground="#000000")
        self.TLabel3.configure(font="TkDefaultFont")
        self.TLabel3.configure(relief=FLAT)
        self.TLabel3.configure(text='''x''')

        self.TLabel4 = ttk.Label(self.Labelframe1)
        self.TLabel4.place(relx=0.5, rely=0.73, height=19, width=9, y=-12, h=6)
        self.TLabel4.configure(background="#d9d9d9")
        self.TLabel4.configure(foreground="#000000")
        self.TLabel4.configure(font="TkDefaultFont")
        self.TLabel4.configure(relief=FLAT)
        self.TLabel4.configure(text=''',''')

        self.TLabel6 = ttk.Label(self.Labelframe1)
        self.TLabel6.place(relx=0.03, rely=0.75, height=19, width=107, y=-12
                , h=6)
        self.TLabel6.configure(background="#d9d9d9")
        self.TLabel6.configure(foreground="#000000")
        self.TLabel6.configure(font="TkDefaultFont")
        self.TLabel6.configure(relief=FLAT)
        self.TLabel6.configure(text='''Spacing dx, dy:''')
        self.TLabel6.configure(width=107)

        self.TEntry4 = ttk.Entry(self.Labelframe1)
        self.TEntry4.place(relx=0.41, rely=0.74, relheight=0.17, relwidth=0.08
                , y=-12, h=6)
        self.TEntry4.configure(width=26)
        self.TEntry4.configure(takefocus="")
        self.TEntry4.configure(cursor="arrow")

        self.TEntry5 = ttk.Entry(self.Labelframe1)
        self.TEntry5.place(relx=0.56, rely=0.74, relheight=0.17, relwidth=0.08
                , y=-12, h=6)
        self.TEntry5.configure(width=26)
        self.TEntry5.configure(takefocus="")
        self.TEntry5.configure(cursor="arrow")

        self.Labelframe2 = LabelFrame(top)
        self.Labelframe2.place(relx=0.0, rely=0.41, relheight=0.42, relwidth=0.5)

        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(text='''Height distribution''')
        self.Labelframe2.configure(background="#d9d9d9")
        self.Labelframe2.configure(highlightbackground="#d9d9d9")
        self.Labelframe2.configure(highlightcolor="black")
        self.Labelframe2.configure(width=160)

        self.TLabel5 = ttk.Label(self.Labelframe2)
        self.TLabel5.place(relx=0.06, rely=0.24, height=19, width=67, y=-12, h=6)

        self.TLabel5.configure(background="#d9d9d9")
        self.TLabel5.configure(foreground="#000000")
        self.TLabel5.configure(font="TkDefaultFont")
        self.TLabel5.configure(relief=FLAT)
        self.TLabel5.configure(text='''Rms height:''')

        self.TEntry6 = ttk.Entry(self.Labelframe2)
        self.TEntry6.place(relx=0.56, rely=0.24, relheight=0.16, relwidth=0.28
                , y=-12, h=6)
        READONLY = 'readonly'
        self.TEntry6.configure(state=READONLY)
        self.TEntry6.configure(width=46)
        self.TEntry6.configure(takefocus="")
        self.TEntry6.configure(cursor="arrow")

        self.TLabel7 = ttk.Label(self.Labelframe2)
        self.TLabel7.place(relx=0.06, rely=0.49, height=19, width=57, y=-12, h=6)

        self.TLabel7.configure(background="#d9d9d9")
        self.TLabel7.configure(foreground="#000000")
        self.TLabel7.configure(font="TkDefaultFont")
        self.TLabel7.configure(relief=FLAT)
        self.TLabel7.configure(text='''Skewness:''')

        self.TLabel8 = ttk.Label(self.Labelframe2)
        self.TLabel8.place(relx=0.06, rely=0.73, height=19, width=49, y=-12, h=6)

        self.TLabel8.configure(background="#d9d9d9")
        self.TLabel8.configure(foreground="#000000")
        self.TLabel8.configure(font="TkDefaultFont")
        self.TLabel8.configure(relief=FLAT)
        self.TLabel8.configure(text='''Kurtosis:''')

        self.TEntry7 = ttk.Entry(self.Labelframe2)
        self.TEntry7.place(relx=0.56, rely=0.49, relheight=0.16, relwidth=0.28
                , y=-12, h=6)
        self.TEntry7.configure(takefocus="")
        self.TEntry7.configure(cursor="arrow")

        self.TEntry8 = ttk.Entry(self.Labelframe2)
        self.TEntry8.place(relx=0.56, rely=0.73, relheight=0.16, relwidth=0.28
                , y=-12, h=6)
        self.TEntry8.configure(takefocus="")
        self.TEntry8.configure(cursor="arrow")

        self.Labelframe4 = LabelFrame(top)
        self.Labelframe4.place(relx=0.5, rely=0.41, relheight=0.42, relwidth=0.5)

        self.Labelframe4.configure(relief=GROOVE)
        self.Labelframe4.configure(foreground="black")
        self.Labelframe4.configure(text='''Correlation function''')
        self.Labelframe4.configure(background="#d9d9d9")
        self.Labelframe4.configure(width=160)

        self.TLabel9 = ttk.Label(self.Labelframe4)
        self.TLabel9.place(relx=0.06, rely=0.24, height=19, width=30, y=-12, h=6)

        self.TLabel9.configure(background="#d9d9d9")
        self.TLabel9.configure(foreground="#000000")
        self.TLabel9.configure(font="TkDefaultFont")
        self.TLabel9.configure(relief=FLAT)
        self.TLabel9.configure(text='''Type''')

        self.TCombobox1 = ttk.Combobox(self.Labelframe4)
        self.TCombobox1.place(relx=0.44, rely=0.24, relheight=0.16, relwidth=0.41
                , y=-12, h=6)
        self.TCombobox1.configure(textvariable=V2_support.combobox)
        self.TCombobox1.configure(width=63)
        self.TCombobox1.configure(takefocus="")

        self.TLabel10 = ttk.Label(self.Labelframe4)
        self.TLabel10.place(relx=0.06, rely=0.49, height=19, width=36, y=-12
                , h=6)
        self.TLabel10.configure(background="#d9d9d9")
        self.TLabel10.configure(foreground="#000000")
        self.TLabel10.configure(font="TkDefaultFont")
        self.TLabel10.configure(relief=FLAT)
        self.TLabel10.configure(text='''n x m:''')

        self.TEntry9 = ttk.Entry(self.Labelframe4)
        self.TEntry9.place(relx=0.44, rely=0.49, relheight=0.16, relwidth=0.16
                , y=-12, h=6)
        self.TEntry9.configure(width=25)
        self.TEntry9.configure(takefocus="")
        self.TEntry9.configure(cursor="arrow")

        self.TLabel11 = ttk.Label(self.Labelframe4)
        self.TLabel11.place(relx=0.63, rely=0.49, height=19, width=16, y=-12
                , h=6)
        self.TLabel11.configure(background="#d9d9d9")
        self.TLabel11.configure(foreground="#000000")
        self.TLabel11.configure(font="TkDefaultFont")
        self.TLabel11.configure(relief=FLAT)
        self.TLabel11.configure(text='''x''')
        self.TLabel11.configure(width=16)

        self.TEntry10 = ttk.Entry(self.Labelframe4)
        self.TEntry10.place(relx=0.69, rely=0.49, relheight=0.16, relwidth=0.16
                , y=-12, h=6)
        self.TEntry10.configure(takefocus="")
        self.TEntry10.configure(cursor="arrow")

        self.TLabel12 = ttk.Label(self.Labelframe4)
        self.TLabel12.place(relx=0.06, rely=0.73, height=19, width=38, y=-12
                , h=6)
        self.TLabel12.configure(background="#d9d9d9")
        self.TLabel12.configure(foreground="#000000")
        self.TLabel12.configure(font="TkDefaultFont")
        self.TLabel12.configure(relief=FLAT)
        self.TLabel12.configure(text='''Alpha:''')

        self.TEntry11 = ttk.Entry(self.Labelframe4)
        self.TEntry11.place(relx=0.44, rely=0.73, relheight=0.16, relwidth=0.41
                , y=-12, h=6)
        self.TEntry11.configure(width=56)
        self.TEntry11.configure(takefocus="")
        self.TEntry11.configure(cursor="arrow")

        self.TButton1 = ttk.Button(top)
        self.TButton1.place(relx=0.03, rely=0.88, height=25, width=113)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Generate surface''')
        self.TButton1.configure(width=113)

        self.TButton2 = ttk.Button(top)
        self.TButton2.place(relx=0.41, rely=0.88, height=25, width=76)
        self.TButton2.configure(takefocus="")
        self.TButton2.configure(text='''Diagnostics''')

        self.TButton3 = ttk.Button(top)
        self.TButton3.place(relx=0.69, rely=0.88, height=25, width=76)
        self.TButton3.configure(takefocus="")
        self.TButton3.configure(text='''Save as''')






if __name__ == '__main__':
    vp_start_gui()



