#############################################################################
# Generated by PAGE version 4.14
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.lab41
    set site_3_0 $base.lab42
    set site_3_0 $base.lab46
    set site_3_0 $base.lab53
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 490x320+830+270
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1354 733
    wm minsize $top 124 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "MARS"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    labelframe $top.lab41 \
        -foreground black -text {Surface parameters} -background {#d9d9d9} \
        -height 125 -highlightcolor black -width 260 
    vTcl:DefineAlias "$top.lab41" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab41
    ttk::label $site_3_0.tLa40 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text {Number of attempts:} 
    vTcl:DefineAlias "$site_3_0.tLa40" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa44 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text {Surface size N x M:} 
    vTcl:DefineAlias "$site_3_0.tLa44" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa46 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text x 
    vTcl:DefineAlias "$site_3_0.tLa46" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa47 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text , 
    vTcl:DefineAlias "$site_3_0.tLa47" "TLabel4" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa52 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text {Spacing dx, dy:} 
    vTcl:DefineAlias "$site_3_0.tLa52" "TLabel6" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi42 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from 1.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable N -to 1000.0 
    vTcl:DefineAlias "$site_3_0.spi42" "Spinbox1" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi43 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from 1.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable M -to 1000.0 
    vTcl:DefineAlias "$site_3_0.spi43" "Spinbox2" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi44 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from 1.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable dx -to 1000.0 
    vTcl:DefineAlias "$site_3_0.spi44" "Spinbox3" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi45 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from 1.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable dy -to 1000.0 
    vTcl:DefineAlias "$site_3_0.spi45" "Spinbox4" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi46 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from 1.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -state disabled -textvariable attempts \
        -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi46" "Spinbox5" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tLa40 \
        -in $site_3_0 -x 10 -y 20 -width 134 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa44 \
        -in $site_3_0 -x 10 -y 50 -width 136 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa46 \
        -in $site_3_0 -x 192 -y 50 -width 13 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa47 \
        -in $site_3_0 -x 192 -y 80 -width 9 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa52 \
        -in $site_3_0 -x 10 -y 80 -width 107 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi42 \
        -in $site_3_0 -x 151 -y 50 -width 36 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi43 \
        -in $site_3_0 -x 210 -y 50 -width 36 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi44 \
        -in $site_3_0 -x 151 -y 80 -width 36 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.spi45 \
        -in $site_3_0 -x 210 -y 80 -width 36 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.spi46 \
        -in $site_3_0 -x 151 -y 20 -width 95 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab42 \
        -foreground black -text {Height distribution} -background {#d9d9d9} \
        -height 135 -highlightcolor black -width 240 
    vTcl:DefineAlias "$top.lab42" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab42
    ttk::label $site_3_0.tLa39 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text {Rms height:} 
    vTcl:DefineAlias "$site_3_0.tLa39" "TLabel5" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa41 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text Skewness: 
    vTcl:DefineAlias "$site_3_0.tLa41" "TLabel7" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa42 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text Kurtosis: 
    vTcl:DefineAlias "$site_3_0.tLa42" "TLabel8" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi47 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from 1.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -state disabled -textvariable rmsheight \
        -to 1000.0 
    vTcl:DefineAlias "$site_3_0.spi47" "Spinbox6" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi48 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from 0.0 -highlightbackground black -highlightcolor black \
        -increment 0.1 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable skewness -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi48" "Spinbox7" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi49 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from 0.0 -highlightbackground black -highlightcolor black \
        -increment 0.1 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable kurtosis -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi49" "Spinbox8" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tLa39 \
        -in $site_3_0 -x 10 -y 30 -anchor nw -bordermode ignore 
    place $site_3_0.tLa41 \
        -in $site_3_0 -x 10 -y 60 -anchor nw -bordermode ignore 
    place $site_3_0.tLa42 \
        -in $site_3_0 -x 10 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.spi47 \
        -in $site_3_0 -x 110 -y 28 -width 95 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_3_0.spi48 \
        -in $site_3_0 -x 110 -y 60 -width 95 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_3_0.spi49 \
        -in $site_3_0 -x 110 -y 90 -width 95 -height 20 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab46 \
        -foreground black -text {Correlation function} -background {#d9d9d9} \
        -height 135 -highlightcolor black -width 240 
    vTcl:DefineAlias "$top.lab46" "Labelframe4" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab46
    ttk::label $site_3_0.tLa47 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text Type: 
    vTcl:DefineAlias "$site_3_0.tLa47" "TLabel9" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_3_0.tCo48 \
        -values {{"Exponential"}} -textvariable acf_type -foreground {} \
        -background {} -takefocus {} -cursor arrow 
    vTcl:DefineAlias "$site_3_0.tCo48" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa49 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text {n x m:} 
    vTcl:DefineAlias "$site_3_0.tLa49" "TLabel10" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa52 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text x 
    vTcl:DefineAlias "$site_3_0.tLa52" "TLabel11" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa56 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text Alpha: 
    vTcl:DefineAlias "$site_3_0.tLa56" "TLabel12" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi50 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from 1.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable n -to 1000.0 
    vTcl:DefineAlias "$site_3_0.spi50" "Spinbox9" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi51 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from 1.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable m -to 1000.0 
    vTcl:DefineAlias "$site_3_0.spi51" "Spinbox10" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi52 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from 0.0 -highlightbackground black -highlightcolor black \
        -increment 0.5 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable alpha -to 360.0 
    vTcl:DefineAlias "$site_3_0.spi52" "Spinbox11" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tLa47 \
        -in $site_3_0 -x 10 -y 30 -anchor nw -bordermode ignore 
    place $site_3_0.tCo48 \
        -in $site_3_0 -x 90 -y 30 -width 125 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa49 \
        -in $site_3_0 -x 10 -y 60 -anchor nw -bordermode ignore 
    place $site_3_0.tLa52 \
        -in $site_3_0 -x 148 -y 60 -width 16 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa56 \
        -in $site_3_0 -x 10 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.spi50 \
        -in $site_3_0 -x 90 -y 60 -width 45 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.spi51 \
        -in $site_3_0 -x 170 -y 60 -width 45 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.spi52 \
        -in $site_3_0 -x 90 -y 90 -width 125 -height 21 -anchor nw \
        -bordermode ignore 
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu62 \
        -takefocus {} -text {Generate surface} 
    vTcl:DefineAlias "$top.tBu62" "TButton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu63 \
        -takefocus {} -text Diagnostics -state disabled 
    vTcl:DefineAlias "$top.tBu63" "TButton2" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu64 \
        -takefocus {} -text {Save as} -state disabled 
    vTcl:DefineAlias "$top.tBu64" "TButton3" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu38 \
        -takefocus {} -text {Advanced settings} 
    vTcl:DefineAlias "$top.tBu38" "TButton4" vTcl:WidgetProc "Toplevel1" 1
    labelframe $top.lab53 \
        -foreground black -text {Program output} -background {#d9d9d9} \
        -height 125 -width 220 
    vTcl:DefineAlias "$top.lab53" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab53
    text $site_3_0.tex54 \
        -background white -font TkTextFont -foreground black -height 95 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -state disabled \
        -width 200 -wrap word 
    .top37.lab53.tex54 configure -font TkTextFont
    .top37.lab53.tex54 insert end text
    vTcl:DefineAlias "$site_3_0.tex54" "Text1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tex54 \
        -in $site_3_0 -x 10 -y 20 -width 200 -relwidth 0 -height 95 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab41 \
        -in $top -x 0 -y 0 -width 260 -relwidth 0 -height 125 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab42 \
        -in $top -x 0 -y 130 -width 240 -relwidth 0 -height 135 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 250 -y 130 -width 240 -relwidth 0 -height 135 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.tBu62 \
        -in $top -x 10 -y 280 -width 133 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu63 \
        -in $top -x 295 -y 280 -width 96 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu64 \
        -in $top -x 400 -y 280 -width 76 -height 25 -anchor nw \
        -bordermode ignore 
    place $top.tBu38 \
        -in $top -x 154 -y 280 -width 130 -height 25 -anchor nw \
        -bordermode ignore 
    place $top.lab53 \
        -in $top -x 270 -y 0 -width 220 -relwidth 0 -height 125 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

