#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Aug 09, 2018 02:56:55 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global N
    N = StringVar()
    global M
    M = StringVar()
    global dx
    dx = StringVar()
    global dy
    dy = StringVar()
    global attempts
    attempts = StringVar()
    global rmsheight
    rmsheight = StringVar()
    global skewness
    skewness = StringVar()
    global kurtosis
    kurtosis = StringVar()
    global acf_type
    acf_type = StringVar()
    global n
    n = StringVar()
    global m
    m = StringVar()
    global alpha
    alpha = StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import V2
    V2.vp_start_gui()


